### PR TITLE
feat: add driverInfo to mongodb component

### PR DESCRIPTION
**Pull request by nbbeeken**
#### What is changing?

[NODE-6240](https://jira.mongodb.org/browse/NODE-6240)

Hello! 👋🏻 I am adding [`driverInfo`](https://mongodb.github.io/node-mongodb-native/6.8/interfaces/DriverInfo.html) to the MongoClient construction in the MongoDBAtlas component. 

#### What is the motivation for this change?

This field is intended for libraries wrapping the driver to push relevant information to the client metadata sent along with the initial handshake during connection creation. This information can be viewed in server logs to assist with debugging the source of a connection issue. It also provides data for determining what combined use cases the driver is supporting ([ex. mongoose](https://github.com/Automattic/mongoose/blob/2d4b8c2995251b8ece99da72a0fe1ba4481c8d18/lib/drivers/node-mongodb-native/connection.js#L295-L298)).

Ideally, I would like to set the Flowise version in addition to the name, I found a getVersion helper in `server/` but not something similar in `components/`, could I port that over? or is there a preferred way to obtain the version?

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
thanks for the update!

yeah for now you can copy the same function from `server`, currently `components` have no access to functions in `server`

**Comment by nbbeeken** [comment]
Hey @HenryHengZJ, let me know if what I have works, happy to add coverage or make changes to align with the project, thanks for taking a look!

**Comment by HenryHengZJ** [comment]
that should works, have you tried if you are able to see the version from your side (Mongo)

**Comment by nbbeeken** [comment]
Took me a bit to get setup, but yes!

Here's a sample server log line:
```
{"t":{"$date":"2024-07-12T16:43:18.650-04:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"127.0.0.1:52726","client":"conn1","doc":{"driver":{"name":"nodejs|Flowise","version":"6.3.0|1.8.5"},"platform":"Node.js v18.20.4, LE","os":{"name":"darwin","architecture":"arm64","version":"23.5.0","type":"Darwin"}}}}
```

The important bit being this part:

`{"driver":{"name":"nodejs|Flowise","version":"6.3.0|1.8.5"}`

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
awesome thanks @nbbeeken !

**Pull request merged**
