### PR TITLE
Feat/added chattBaiduWenxin chat model

### PR DESCRIPTION
**Pull request by Mubashirshariq**
Fixes: #2751 
Added ChatBaiduWenxin chat model

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
thank you! some linting issue

**Comment by iceycc** [comment]
Thanks for you code, I used it。but It seems to require two keys, and need streaming。 like：
```typescript
        const obj: Partial<ChatBaiduWenxin> = {
            streaming: true,
            baiduApiKey,
            baiduSecretKey,
            modelName,
            temperature: temperature ? parseFloat(temperature) : undefined
        }

    }
```

**Comment by Mubashirshariq** [comment]
@iceycc i have done the required changes

**Review by HenryHengZJ — APPROVED** [review]

**Comment by iceycc** [comment]
In langchanJs ,  Wenxin becomes Qianfan,  [here](https://js.langchain.com/v0.2/docs/integrations/chat/baidu_qianfan) ,  and then I refer to yours and it says an error ： stream.getReader is not a function。

See details here：
https://github.com/FlowiseAI/Flowise/issues/2786

**Pull request merged**
