### PR TITLE
Feature/Spider (open-source web scraper & crawler)

### PR DESCRIPTION
**Pull request by WilliamEspegren**
[Spider](https://spider.cloud/) is the [fastest](https://github.com/spider-rs/spider/blob/main/benches/BENCHMARKS.md#benchmark-results) open source scraper & crawler that returns LLM-ready data.

Now you can scrape and crawl any website using spider.

Twitter handle: [@WilliamEspegren](https://x.com/WilliamEspegren)

image

This PR was inspired by #2728

### CODE REVIEW

**Comment by WilliamEspegren** [comment]
image

How can I fix this?

**Comment by WilliamEspegren** [comment]
Now "pnpm lint" is passing :)

**Comment by toi500** [comment]
@WilliamEspegren how to test this PR since you dont offer free trial or free any credit? https://spider.cloud/credits/new

**Comment by toi500** [comment]
@WilliamEspegren how to test this PR since you dont offer free trial or any free credit? https://spider.cloud/credits/new

**Comment by WilliamEspegren** [comment]
> @WilliamEspegren how to test this PR since you dont offer free trial or any free credit? https://spider.cloud/credits/new
DM me on twitter, I think I can set you up with an account :)

**Comment by toi500** [comment]
> > @WilliamEspegren how to test this PR since you dont offer free trial or any free credit? https://spider.cloud/credits/new
> 
> DM me on twitter, I think I can set you up with an account :)

Thank you, waiting for your response.

image

**Comment by toi500** [comment]
@WilliamEspegren I just tested and the integration works, very fast actually. Impresed.

But the quaility of the data scrappered is a bit dirty with the default values (raw). Check this out:

capture_240630_165819

Would it be possible to add those good options you have in your dashboard to the node itself? At least the request/return format should be added so this can be more usable from Flowise.

capture_240630_171427

**Comment by WilliamEspegren** [comment]
@toi500 Imgs transforms to markdown if it does not have certain properties for position. 

Spider, we are in the middle of further cleaning the markdown.

**Comment by toi500** [comment]
@WilliamEspegren got it.

What about the metadata? This is going to be important since the Flowise team is working to add a custom retriever node that allows users to specify what metadata they'd like to be included in the LLM context after a query.

image

**Comment by WilliamEspegren** [comment]
@toi500 a metadata node sounds really interesting! I believe I have made a flag for metadata in the node, but what format should the metadata be in? I can change it to return metadata on default.

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
yeah agree with @toi500 , overall very fast scraping experience. If the metadata can be something like: 
```
{
  source: 'https://example.com',
  loc: {...}
}
```

**Comment by WilliamEspegren** [comment]
Metadata is now returned likes this: 
image

**Comment by WilliamEspegren** [comment]
@HenryHengZJ the lint gods is now happy :)

**Comment by HenryHengZJ** [comment]
thank you!

**Pull request merged**
