### PR TITLE
Together AI llms

### PR DESCRIPTION
**Pull request by jiabaow**
#1400 
This PR adds support for TogetherAI LLM.
Screenshot 2024-05-20 at 20 50 34

TODO:
- The streaming mode is currently unusable. When activated, it generates an error message indicating issues with JSON parsing: [ERROR]: [server]: Error: Unexpected token 'd', "data: {"id"... is not valid JSON. It appears to come from the server side.
- safetyModel and logprobs parameters are not included in the current implementation.

### CODE REVIEW

**Review by HenryHengZJ — APPROVED** [review]
looks good! thanks @jiabaow !

**Comment by HenryHengZJ** [comment]
@jiabaow in order to add streaming, can you add `togetherAI` to this line [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/utils/index.ts#L1092)

**Comment by jiabaow** [comment]
@HenryHengZJ Thanks for your reply, however, the problem persists after adding `togetherAI` to src/utils: 
Screenshot 2024-05-23 at 14 52 07

**Comment by HenryHengZJ** [comment]
I see, its okay we can remove it the line then. Lets have it not streaming for now. Since the ChatTogetherAI is able to stream

**Review by HenryHengZJ — APPROVED** [review]

**Pull request merged**
