### PR TITLE
marketplace cards text and images overflow fixed

### PR DESCRIPTION
**Pull request by siddiqss**
**Issue**
Cards in marketplace were not showing the complete text and images.

**How it looked before**

Screenshot 2023-05-14 at 4 33 35 PM

**How it looks now**

Screenshot 2023-05-14 at 5 05 52 PM

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
Awesome! Are the changes applied on Chatflows as well?

**Comment by siddiqss** [comment]
Chatflows are using same ItemCard so yes.

**Comment by siddiqss** [comment]
**Here's how chatflow cards looked like**

Screenshot 2023-05-14 at 5 46 20 PM

**How they look like now**

Screenshot 2023-05-14 at 5 46 57 PM

**Review by HenryHengZJ — APPROVED** [review]
Looks good! Thank you @siddiqss !

**Pull request merged**
