### PR TITLE
Enable/disable variables in override configuration

### PR DESCRIPTION
**Pull request by 0xi4o**
### Add ability to enable/disable which variables can be overriden during external predictions via API or `chatflowConfig` property in embeds

- Add Security tab in chatflow/agentflow configuration. Rate limit and allowed domains settings is now under this tab.
Flowise-Low-code-LLM-apps-builder-11-08-2024_10_34_PM
Flowise-Low-code-LLM-apps-builder-11-08-2024_10_35_PM (1)

- In Embed/API Code dialog, show whether a property can be overriden based on the saved security settings
Flowise-Low-code-LLM-apps-builder-11-08-2024_10_35_PM
Flowise-Low-code-LLM-apps-builder-11-08-2024_10_36_PM

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
Dividers and clear headings for each section:
image

**Comment by HenryHengZJ** [comment]
Crashed: 
image
image

**Comment by HenryHengZJ** [comment]
Override Config not updated with the flow:

1.) Initially have 3 nodes:
image

2.) Added new ChatPromptTemplate:
image

3.) Click Config, still the same 3 nodes for overrideconfig:
image

Expected to see updated nodes

**Comment by HenryHengZJ** [comment]
Only have 1 save changes button, not 3 with different wordings: 
image

**Comment by 0xi4o** [comment]
@HenryHengZJ fixed crashing and config not updating. Also updated the UI for security tab.

Flowise-Low-code-LLM-apps-builder-11-11-2024_06_00_PM

**Comment by HenryHengZJ** [comment]
- [ ]  Upsert Vector OverrideConfig not working
- [ ] Agentflow OverrideConfig not working

**Comment by ltechconsultancy** [comment]
Since this update uploading via upsert API doesnt work anymore. https://github.com/FlowiseAI/Flowise/issues/3560

**Pull request merged**
