### PR TITLE
Feature/add vertex ai chatmodel

### PR DESCRIPTION
**Pull request by Yongtae723**
add component of [vertex ai chatmodel](https://js.langchain.com/docs/api/chat_models_googlevertexai/classes/ChatGoogleVertexAI).

other worry about this PR is the same with #679

### CODE REVIEW

**Comment by chungyau97** [comment]
Hi @Yongtae723,

Thanks for the PR. 😄 

Could you kindly share the result of integration of Vertex AI chat model in screenshots/video format?
[video example](https://github.com/FlowiseAI/Flowise/pull/114)
[screenshots example](https://github.com/FlowiseAI/Flowise/pull/698)

**Comment by Yongtae723** [comment]
Sure.

how to manage credential file is discussed in #679 .
After determination how credential managed, I will modify this PR based on that.

vertex AI chatmodel

**Comment by Yongtae723** [comment]
I finally finish with the same way of https://github.com/FlowiseAI/Flowise/pull/679

vertex ai chatmodel

**Comment by chungyau97** [comment]
Hi @Yongtae723 

The code looks good to me in #681, #680, #679.

But I'm curious on merging this 3 branch, as the `GoogleAuth.credential.ts` is duplicated on 3 branch.

cc @HenryHengZJ

**Comment by Yongtae723** [comment]
Hi @chungyau97 
not only `GoogleAuth.credential.ts` but also `packages/components/package.json` is changed because of long discussion in #679.

so how about following way?

I will merge https://github.com/FlowiseAI/Flowise/pull/681, https://github.com/FlowiseAI/Flowise/pull/680, https://github.com/FlowiseAI/Flowise/pull/679 by myself and send new single PR again.
Then I will close https://github.com/FlowiseAI/Flowise/pull/681, https://github.com/FlowiseAI/Flowise/pull/680, https://github.com/FlowiseAI/Flowise/pull/679.

**Comment by HenryHengZJ** [comment]
> Hi @chungyau97 not only `GoogleAuth.credential.ts` but also change of `packages/components/package.json` is duplicated because of long discussion in #679.
> 
> so how about following way?
> 
> I will merge #681, #680, #679 in my forked repository by myself and send new single PR again. Then I will close #681, #680, #679.

yep that sounds good!

**Comment by Yongtae723** [comment]
I got it!

thank you!

**Pull request closed without merging**
