### PR TITLE
Add $flow to Variable Resolution in Flow Building Process

### PR DESCRIPTION
**Pull request by raffareis**
## Changes Overview

This PR enhances the variable resolution process in the flow building mechanism, particularly focusing on the `buildFlow` and `getVariableValue` functions.

### Key Updates

1. **Flow Options Enhancement**
   - Added a new `options` object in the `buildFlow` function:
     ```typescript
     const options: ICommonObject = {
         chatflowid,
         chatId,
         sessionId,
         chatHistory
     }
     ```

2. **Variable Resolution Improvements**
   - Updated `resolveVariables` and `getVariableValue` functions to accept and utilize the new `options` parameter.

3. **Flow-specific Variable Support**
   - Implemented handling for variables starting with `$flow.` in the `getVariableValue` function:
     ```typescript
     if (variableFullPath.startsWith('$flow.') && options) {
         const variableValue = get(options, variableFullPath.replace('$flow.', ''))
         if (variableValue) {
             variableDict[`{{${variableFullPath}}}`] = variableValue
             returnVal = returnVal.split(`{{${variableFullPath}}}`).join(variableValue)
         }
     }
     ```

## Rationale

These changes allow for more flexible and context-aware variable resolution within the flow building process. By introducing the `options` object and supporting `$flow.` prefixed variables, we enable access to flow-specific data like `chatflowid`, `chatId`, `sessionId`, and `chatHistory` during variable resolution.

Also it can be used to enhance filtering and logic in any flow input:
image

## Testing

image
image
image

## Notes for Reviewers

- Pay special attention to the variable resolution logic in `getVariableValue`.
- Consider if there are any edge cases in flow-specific variable usage that should be addressed.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
@raffareis I tried something like this:

image

but somehow the $flow is not getting replaced with value:
image

**Comment by raffareis** [comment]
@HenryHengZJ nice catch. Here we go. 
https://github.com/FlowiseAI/Flowise/pull/3075/commits/bbf8cee533ff2ecdb7c90df5a33e53ea5c322bb9

image
image

**Comment by raffareis** [comment]
Also did a little refactor. Instead of an additional parameter, I merged overrideConfig and options into flowData. Bonus that it will work for agent flows as well because of that.

https://github.com/FlowiseAI/Flowise/pull/3075/commits/d3662bc9162d72ec1727a7a10d7bec70067a56cd

**Review by HenryHengZJ — APPROVED** [review]
thanks @raffareis !

**Pull request merged**
