### PR TITLE
[BUG] Agentflow Not Functioning Properly in Flowise 2.0.0 #2847

### PR DESCRIPTION
**Pull request by seonghobae**
🛠️ Supervisor.ts -> Removed summarization fields.

### CODE REVIEW

**Comment by toi500** [comment]
While final summarization enhances contextual consistency between user queries and supervisor outputs, aiding task resumption with the introduction of the new Agent Memory node, it can also restrict the range of applications a Multi-Agent system can handle when a clean final output is essential.

So, can we make this optional?

**Comment by seonghobae** [comment]
> While final summarization enhances contextual consistency between user queries and supervisor outputs, aiding task resumption with the introduction of the new Agent Memory node, it can also restrict the range of applications a Multi-Agent system can handle when a clean final output is essential.
> 
> So, can we make this optional?

The summarisation feature introduced in version 2.0.0 broke the behaviour of all the workers I created. I'm not a typescript expert, just a business data analyst, so this commit is to revert back to the previous state. In fact, it's not even clear from the git logs that I can revert this commit as a business data analyst, but I can confirm that removing the summary itself brought back the behaviour I intended. If the summary can be interpreted differently by different models and cause misbehaviour, I'd rather not have it. If you believe it should be an option, then I think it should be turned off by default.

**Comment by HenryHengZJ** [comment]
Understood, will see if we can create an optional field for supervisor, and provide summary only when user select so

**Comment by HenryHengZJ** [comment]
@seonghobae I've created a PR that brings back the old functionality, and move summarization as an optional field.

**Pull request closed without merging**
