### PR TITLE
Add chat model open ai proxy url params

### PR DESCRIPTION
**Pull request by thanhtung100397**
Add Proxy URL option for Open AI chat model

image

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
awesome! are you able to test is using proxy?

**Comment by wangsp188** [comment]
great, i will try

> Add Proxy URL option for Open AI chat model
> 
> image

**Comment by thanhtung100397** [comment]
I have setup a squid server as proxy and it's worked, hope this can help anyone got this open ai api error: `unsupported_country_region_territory`

**Comment by wangsp188** [comment]
> I have setup a squid server as proxy and it's worked, hope this can help anyone got this open ai api error: `unsupported_country_region_territory`

what time the commit will merge to main branch?

**Comment by thanhtung100397** [comment]
> > I have setup a squid server as proxy and it's worked, hope this can help anyone got this open ai api error: `unsupported_country_region_territory`
> 
> what time the commit will merge to main branch?

i dont have any permission to merge so anyone can help?

**Review by HenryHengZJ — APPROVED** [review]
thanks @thanhtung100397

**Comment by wangsp188** [comment]
> thanks @thanhtung100397

what to use the param?
i have build a proxy for openai.
image

**Comment by thanhtung100397** [comment]
> > thanks @thanhtung100397
> 
> what to use the param? i have build a proxy for openai. image
> 
> this is error log 2024-09-10 09:25:36 [INFO]: [server]: Chatflow dc4c428f-5278-465e-ad9a-bf6b3bdb5074 added into ChatflowPool 2024-09-10 09:27:01 [ERROR]: [server]: Error: Connection error. Error: Connection error. at OpenAI.makeRequest (/Users/dexwang/sourcecode/Flowise/node_modules/.pnpm/openai@4.51.0_encoding@0.1.13/node_modules/openai/core.js:304:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /Users/dexwang/sourcecode/Flowise/node_modules/.pnpm/@langchain+openai@0.0.30_encoding@0.1.13_langchain@[0.2.11_@aws-sdk](mailto:0.2.11_@aws-sdk)+client-s3@3.529.1_@aws-sdk_xdehwmr5gttavnvrwzf5jjmfv4/node_modules/@langchain/openai/dist/chat_models.cjs:760:29 at async RetryOperation._fn (/Users/dexwang/sourcecode/Flowise/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)

You can follow my step

image

image

Here is the sample input for proxy url

(proxy without user/pass): http://127.0.0.1:3128
(proxy with user/pass): http://user:pass@127.0.0.1:3128

**Comment by Rrrrnnyg** [comment]
Hi, do I need to fill in the proxy URL every time I use OpenAI API? 
Is there a better way to management?

**Comment by thanhtung100397** [comment]
> Hi, do I need to fill in the proxy URL every time I use OpenAI API? Is there a better way to management?

At the moment, you need to input proxy url for every new ChatOpenAI node added to chatflow

I know it's better if we have a new ui to manage proxy url globaly... just like api key management ui

**Pull request merged**
