### PR TITLE
feat: additional metadata added to Spider tool

### PR DESCRIPTION
**Pull request by WilliamEspegren**
This updates the Spider tool to include optional additional metadata that can be used when eg. indexing vector DB's

Twitter: [@WilliamEspegren](https://x.com/WilliamEspegren)
additional_metadata

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
Since you have added metadata, might as well to add `omitMetadataKeys`, you can refer to other doc loaders for that

**Comment by WilliamEspegren** [comment]
I am on it :)

**Comment by WilliamEspegren** [comment]
@HenryHengZJ Omit is added :) 
additional_metadata_omit

**Comment by WilliamEspegren** [comment]
@HenryHengZJ ready to merge :)

**Review by HenryHengZJ — APPROVED** [review]
awesome thank you!

**Pull request merged**
