### PR TITLE
Feature/Add Groq Whisper support

### PR DESCRIPTION
**Pull request by ghondar**
- Introduced a new speech-to-text provider, Groq Whisper, in both the backend and UI components.
- Updated SpeechToTextType to include GROQ_WHISPER.
- Implemented Groq client integration for audio transcription with customizable model, language, and temperature options.
- Added UI elements for Groq Whisper configuration, including input fields for model, language, and temperature settings.
Screenshot 2024-12-13 at 5 46 26 PM

### CODE REVIEW

**Review by HenryHengZJ — APPROVED** [review]
thank you so much @ghondar !

**Comment by almirb** [comment]
Hi @ghondar ! 

I can't save the config after adding Groq Whisper configs.

Here are the logs (I'm on Flowise 2.2.3, using docker image):
image

Can you help?
Thanks!

**Comment by ghondar** [comment]
Hi @almirb , if you have another provider selected, try selecting none first, save and then select Groq Whisper provider

**Comment by almirb** [comment]
> Hi @almirb , if you have another provider selected, try selecting none first, save and then select Groq Whisper provider

It worked like a charm! 
Thanks @ghondar ! What a great addition to Flowise! 💪

**Pull request merged**
