### PR TITLE
Feature/Add LocalAI

### PR DESCRIPTION
**Pull request by HenryHengZJ**
https://github.com/FlowiseAI/Flowise/assets/26460777/88847900-da3c-4da7-a347-89520b21540d

### CODE REVIEW

**Comment by MightEnlightenYou** [comment]
So I tried to replace the ChatOpenAI wrapper with ChatLocalAI in the AutoGPT template but it won't connect the output from ChatLocalAI to the input of the AutoGPT wrapper.

Anyone got any ideas about how to solve this?

**Comment by DonXtasy** [comment]
How do you use LocalAI as Embedding? 
image

**Comment by HenryHengZJ** [comment]
Will be creating an embedding node for LocalAI

**Comment by HenryHengZJ** [comment]
LocalAI Embedding node is merged now - https://github.com/FlowiseAI/Flowise/pull/300

**Comment by HenryHengZJ** [comment]
@DonXtasy not yet pushed the new localai embeddings to docker. For now you can update locally by:

`git pull`
`yarn build`
`yarn start`

**Comment by mozg31337** [comment]
A bit of a daft question from a beginner. I am trying to use my llama.cpp model files stored locally on my computer. How do I expose them to the ChatLocalAI tool? I can't specify the path to the local file. It seem to want to access it via http. Thanks

**Comment by gregorym** [comment]
Is there any documentation for this?

**Comment by chungyau97** [comment]
Hi @gregorym,

Here are the documentation of LocalAI:
1. [LocalAI Embeddings](https://docs.flowiseai.com/embeddings/localai-embeddings)
2. [ChatLocalAI](https://docs.flowiseai.com/chat-models/chatlocalai)

**Pull request merged**
