### PR TITLE
Correct "as" casing

### PR DESCRIPTION
**Pull request by dillfrescott**
This was driving me crazy when building Flowise as it would give a warning that the casing was not consistent.

### CODE REVIEW

**Comment by dillfrescott** [comment]
Also removed "version" from docker compose because that is deprecated

**Comment by HenryHengZJ** [comment]
> Also removed "version" from docker compose because that is deprecated. Any modern version of docker will also warn about version being deprecated.

if others are using the old docker engine, do they still need it?

**Comment by HenryHengZJ** [comment]
cool, for now i will just change the casing first

**Comment by dillfrescott** [comment]
Sounds good to me!

**Review by HenryHengZJ — APPROVED** [review]
thanks !

**Pull request merged**
