### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by darthludious**
add devDependencie
 "@babel/plugin-proposal-private-property-in-object": "*"

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
thanks for the PR! is this dependency to address warning message from installation? if so, which one?

**Comment by atishamte** [comment]
@HenryHengZJ yes this is for the warning we get while doing yarn build process

**Comment by HenryHengZJ** [comment]
Think the right place to add this is in `ui/package.json`, will close this and open another PR fo rthat

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/Flowise/pull/686 opened here

**Comment by darthludious** [comment]
Yes sorry. Thank you :)

**Pull request closed without merging**
