### PR TITLE
Feature/Indexing

### PR DESCRIPTION
**Pull request by HenryHengZJ**
Add indexing record manager components:

Screenshot 2024-02-24 013603

image

### CODE REVIEW

**Comment by chungyau97** [comment]
Added fix for `QueryFailedError: SQLITE_RANGE: column index out of range` error when upserting multiple files

**Review by vinodkiran — CHANGES_REQUESTED** [review]

**Comment by vinodkiran** [comment]
> Add indexing record manager components:
> 
> Screenshot 2024-02-24 013603 

Is there an option to see this info/dialog after it is closed from the Upsert Dialog?

**Comment by chungyau97** [comment]
I will add mysql

**Review by chungyau97 — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
@vinodkiran every chatflow now contains a history of upserting regardless of whether the record manager exists:
image

image

**Review by ocflowiseai — APPROVED** [review]
Looks good to me!

**Pull request merged**
