### PR TITLE
feature/Add ChatOllama Function

### PR DESCRIPTION
**Pull request by HenryHengZJ**
image

### CODE REVIEW

**Comment by AtmehEsraa** [comment]
What if I want to engage in conversation without needing to rely on a tool @HenryHengZJ

**Comment by manuelbachl** [comment]
I always receive the response "Agent stopped due to max iterations" (Using llama3 as model)

**Comment by dentro-innovation** [comment]
does ollama function support streaming?
Doesn't seem to me, but wanted to double check

**Comment by erlebach** [comment]
The ChatOllamaFunction seems to have disappeared. It was there in commit 0de7fb85. I could not find it in the code base in `main.cpp`. It might have been deleted inadvertently. @HenryHengZJ

**Comment by dentro-innovation** [comment]
Chat Ollama is very useful btw for using self hosted LLMs, hope we can get it back soon!

**Pull request merged**
