### PR TITLE
Add couchbase vectore store support

### PR DESCRIPTION
**Pull request by prajwal-pai77**
Hey @HenryHengZJ 
In the latest couchbase sdk version, we have added support for Alpine ARM builds. Can you please check if the docker image is successfully built?
Context: https://github.com/FlowiseAI/Flowise/pull/2303
Thanks!

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
awesome! will have a test

**Comment by prajwal-pai77** [comment]
Great! Let us know, Thanks!

**Comment by prajwal-pai77** [comment]
Hi @HenryHengZJ , were you able to test out the docker build?

**Comment by JJK801** [comment]
🙌  thanks @prajwal-pai77

**Review by HenryHengZJ — APPROVED** [review]
thanks @prajwal-pai77 !

**Pull request merged**
