### PR TITLE
feat: add shortcut text hint to the search field

### PR DESCRIPTION
**Pull request by rhumbertgz**
Before
Screenshot 2024-09-26 at 16 08 53
 
After
Screenshot 2024-09-26 at 16 08 09

### CODE REVIEW

**Comment by toi500** [comment]
@rhumbertgz I do not know if this is related to your last PRs, but I just updated, and the Tool and Assistants page does not load any longer. It gets a blank page.

image

**Comment by toi500** [comment]
I just roll back and It Tools and Assistants pages are loading again:

image

**Comment by HenryHengZJ** [comment]
fixing it

**Comment by rhumbertgz** [comment]
@toi500 @HenryHengZJ I found the error and fixed it #3270

Sorry, I didn't check those views :(

**Comment by HenryHengZJ** [comment]
@rhumbertgz can you pull from latest again?

**Comment by rhumbertgz** [comment]
@HenryHengZJ I pulled the latest changes but the problem persists. I will check it again tomorrow morning with fresh eyes. Don’t worry I will find a solution

**Comment by rhumbertgz** [comment]
@HenryHengZJ fixed, it was stupid undefined variable that for some reason my editor and JS didn't complaint about it

**Review by HenryHengZJ — APPROVED** [review]

**Pull request merged**
