### PR TITLE
Fixed CONTRIBUTING.md typo

### PR DESCRIPTION
**Pull request by arugal**
https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#-env-variables

### CODE REVIEW

**Review by HenryHengZJ — APPROVED** [review]

**Comment by arugal** [comment]
@HenryHengZJ  The github action [failed to run](https://github.com/FlowiseAI/Flowise/actions/runs/6622879886/job/18269944096?pr=1122#step:7:29). It looks like the milvus sdk [updated the code](https://github.com/milvus-io/milvus-sdk-node/commit/aae993605767525f183b8839b42d5f807ff02491#diff-711339cdb2ee94466eb03200a75d0194d99e0384ee8ab44a20e5ec149fe8a03dR132). We should lock the version or update the code

**Comment by arugal** [comment]
Is someone already working on it? I can submit a new pr

**Comment by HenryHengZJ** [comment]
can you pull from latest main and try again?

**Comment by arugal** [comment]
> can you pull from latest main and try again?

synchronized. action needs to be approved

**Pull request merged**
