### PR TITLE
Added winston logging

### PR DESCRIPTION
**Pull request by matthias**
- use logger.xxx instead of console.xxx
- added express middleware logging (using jsonl)
- added LOG_PATH as environment variable
- more configs postponed for later iteration

### CODE REVIEW

**Comment by matthias** [comment]
Created a new clean merge

**Review by matthias — COMMENTED** [review]
I understand that you also want to respect the DEBUG setting.

But not sure if the DEBUG flag is the right one to enable / disable request logging at all. Even in a production environment you want HTTP request logging.

I would suggest to move this into the logger.ts / expressRequestLogger -> so it can be configured via config.

**Comment by HenryHengZJ** [comment]
good point @matthias do you reckon we should add another env var like `ENABLE_LOGGING`? This allow user to have flexibiltity to turn on/off loggers if they dont want to burden the system with logs

**Comment by HenryHengZJ** [comment]
You can create another branch base from this branch.

Are you trying to log the output of each component? I was trying to see if we can add the logs output from langchain when the DEBUG is true, as currently they are just printed on the terminal/console

**Comment by HenryHengZJ** [comment]
@matthias I reverted the DEBUG changes and allow logger by default. Let me know if you are still working on this, if not we can merge this and open another PR for the logger on components

**Review by HenryHengZJ — APPROVED** [review]

**Comment by matthias** [comment]
Yes you can merge it ... logger on compnents / flows should be another PR imo.

**Pull request merged**
