### PR TITLE
Tests for backend

### PR DESCRIPTION
**Pull request by mingxin0607**
#1220 
Add test cases for packages/server/src/utils/hub.ts

Run with:
```
node packages/server/test/utils/hub.test.js
```
Output:
```
Test passed: System message prompt
Test passed: Human message prompt
Test passed: AI message prompt
Test passed: Template prompt
Test passed: Empty messages array
```

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
@mingxin0607 thank you for starting the unit test effort, we need this! Is there any other tests cases you were thinking to add? We separated out most functions to `packages/server/src/utils`, they should be good for unit tests

**Comment by mingxin0607** [comment]
> @mingxin0607 thank you for starting the unit test effort, we need this! Is there any other tests cases you were thinking to add? We separated out most functions to `packages/server/src/utils`, they should be good for unit tests

Thank you for your information! I just added a test case for logger.ts under `packages/server/src/utils`, and made a new pull request.
#2484

**Comment by mingxin0607** [comment]
Hello, I accidentally closed this PR before, now I reopen it, hope to hear back from you =)

**Comment by mingxin0607** [comment]
Hello, I notice that this test case has already been merged, so I'm closing this pr.

**Pull request closed without merging**
