### PR TITLE
[Feature] Repair JSON from LLM in StructuredOutputParserAdvanced

### PR DESCRIPTION
**Pull request by JJK801**
Hi Flowise,

I got in trouble with using `StructuredOutputParserAdvanced` with some complex schema: LLM returns broken JSON (wrong quotes, double quote surrounding, etc...)

I added a lib that fixes JSON text before trying to parse it.

### CODE REVIEW

**Comment by JJK801** [comment]
Results are quite impressive, from arround 10% success rate, i now got 100% success (or close to, i didn't have any formatting error since)

**Comment by HenryHengZJ** [comment]
interesting, can you give an example of schema that you were using?

**Comment by JJK801** [comment]
Of course, here is a Zod schema we use for generating a report after a chat session with a client:

```js
z.object({
	title: z.string().describe('A title for the report'),
	type: z
		.string()
		.describe(
			'Type of intervention - e.g., inspection, quality control, troubleshooting, training'
		),
	overview: z.string(),
	steps: z
		.array(z.string())
		.describe('Detailed description of the steps taken during the intervention'),
	summary: z.object({
		short: z
			.string()
			.describe(
				'Short summary of the intervention, mention the name of the user if you have the information'
			),
		long: z.string().describe('Long summary of the intervention')
	}),
	local: z.object({
		totalSteps: z
			.number()
			.describe(
				'Total number of steps in the first level, not counting the substeps, in the whole Procedure'
			),
		stepsCompleted: z
			.number()
			.describe('Steps completed in the first level, not counting the completed substeps')
	}),
	issuesEncountered: z
		.array(z.string())
		.describe('List of issues encountered during the intervention'),
	finalOutcome: z.string().describe('Final outcome of the intervention'),
	tasks: z.object({
		toDo: z
			.array(z.string())
			.describe('Tasks emerging from the intervention that need to be addressed'),
		done: z.array(z.string()).describe('Tasks completed during the intervention'),
		suspended: z.array(z.string()).describe('Pending tasks')
	}),
	sentiments: z.object({
		client: z.array(z.string()).describe('Sentiment analysis of the user'),
		hotliner: z.array(z.string()).describe('Sentiment analysis of the hotliner')
	}),
	machine: z.object({
		type: z.string().describe('Type of machine involved - if applicable, if not then empty')
	})
})
```

Most of the time, the 5~8 firsts keys of the JSON are valid, but the other have errors, mainly using simple quotes or curly quotes.

**Review by HenryHengZJ — APPROVED** [review]
thanks @JJK801 !

**Pull request merged**
