### PR TITLE
Fix CustomFunction deserializing escaped JSON strings

### PR DESCRIPTION
**Pull request by mokeyish**
This PR relates to https://github.com/FlowiseAI/Flowise/pull/1539 . If it is json after unescaping, it will be parsed into a json object.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
can you provide more description or elaboration what this PR trying to solve? screenshot/example of bug/errors/how to replicate the issue

**Comment by mokeyish** [comment]
@HenryHengZJ This PR relates to #1539 . If it is json after unescaping, it will be parsed into a json object.

**Comment by mokeyish** [comment]
图片

**Comment by HenryHengZJ** [comment]
@mokeyish do you have some examples chatflow that I can replicate the issue?

**Comment by mokeyish** [comment]
> @mokeyish do you have some examples chatflow that I can replicate the issue?

In my case it's LLMChain that outputs a JSON string, and then the next node is CustomFunction.

**Comment by HenryHengZJ** [comment]
> > @mokeyish do you have some examples chatflow that I can replicate the issue?
> 
> In my case it's LLMChain that outputs a JSON string, and then the next node is CustomFunction.

does the JSON string contains the escaped characters like `FLOWISE_DOUBLE_QUOTE` ? I was just thinking any downside of handling the conversion of escaped charactes before JSON parsing it

**Comment by mokeyish** [comment]
Yes, it contains `FLOWISE_DOUBLE_QUOTE`, so JSON parsing failed. then in the CustomFunction, it json string other than json object.

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
We will have to do the same for `IfElseFunction.ts` as well

**Comment by mokeyish** [comment]
> We will have to do the same for `IfElseFunction.ts` as well

Did you reply to the wrong place? did you mean #1832 ? IfElseFunction I understand that there are two EndNode branches, and which branch is decided based on the result.  But #1832 says reusing the calculation result of the previous node.

**Comment by HenryHengZJ** [comment]
we have the same logic here - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/utilities/IfElseFunction/IfElseFunction.ts#L104

**Pull request merged**
