### PR TITLE
support pinecone namespace given by vars

### PR DESCRIPTION
**Pull request by niztal**
According to pinecone's [documentation](https://support.pinecone.io/hc/en-us/articles/7884238411165-Using-namespaces-vs-metadata-filtering) the best practice for segmenting a data across multiple customers is to have a dedicated namespace per customer.

If we wish to have a single vector based chatflow (based on pinecone vector store) that should server multiple customers, following the current implementation it is impossible since the provided namespace for pinecone must be fixed.

Having the ability to provide a dynamic namespace via this PR solves this problem.

For example:

```
<script type="module">
        import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js"
        Chatbot.init({
            chatflowid: "e683f528-4f5f-4cf8-8f5b-25f7802c7de1",
            apiHost: "http://localhost:3000",
            chatflowConfig: {
                vars: {
                    customer_id: 'customer_123'
                }
            }
        })
    </script>
```

This script will embed a chatbot that will query its vectors from the **customer_123** namespace

If no overrideConfig is provided (vars) the pinecone namespace will be taken out of the node's input params.

### CODE REVIEW

**Comment by niztal** [comment]
@Jaredude this PR according to your [recommendation](https://github.com/FlowiseAI/Flowise/issues/1690) please review 

@HenryHengZJ

**Comment by niztal** [comment]
@HenryHengZJ can you please review? I really need this to be part of upcoming release 🙏

**Comment by Jaredude** [comment]
I have yet to use Pinecone, so I would not be a good option for testing this update.

**Comment by HenryHengZJ** [comment]
why not just provides the namespace directly?
```
<script type="module">
        import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js"
        Chatbot.init({
            chatflowid: "e683f528-4f5f-4cf8-8f5b-25f7802c7de1",
            apiHost: "http://localhost:3000",
            chatflowConfig: {
                pineconeNamespace: 'abc'
            }
        })
    </script>
```

**Comment by niztal** [comment]
> why not just provides the namespace directly?
> 
> ```
> <script type="module">
>         import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js"
>         Chatbot.init({
>             chatflowid: "e683f528-4f5f-4cf8-8f5b-25f7802c7de1",
>             apiHost: "http://localhost:3000",
>             chatflowConfig: {
>                 pineconeNamespace: 'abc'
>             }
>         })
>     </script>
> ```

I tried it but for some reason (maybe you know to tell) this variable didn't accept but got empty, moreover same as PR https://github.com/FlowiseAI/Flowise/pull/2018, I'm trying to have a convention for flowise's multi tenancy but moving the customer_id , later it can be for other vector stores, LLMs, etc.

@HenryHengZJ @Jaredude

**Comment by HenryHengZJ** [comment]
It's working from my side though, do you see any error?

**Comment by niztal** [comment]
> It's working from my side though, do you see any error?

If it's working I'll change it and commit a fix.

I like your approach

Thanks

**Comment by HenryHengZJ** [comment]
> > It's working from my side though, do you see any error?
> 
> If it's working I'll change it and commit a fix.
> 
> I like your approach
> 
> Thanks

It's already working as it is. You shouldn't need to push additional changes

**Comment by niztal** [comment]
> pineconeNamespace



> > > It's working from my side though, do you see any error?
> > 
> > 
> > If it's working I'll change it and commit a fix.
> > I like your approach
> > Thanks
> 
> It's already working as it is. You shouldn't need to push additional changes

Thanks @HenryHengZJ it's working fine, I'll close this PR

**Pull request closed without merging**
