### PR TITLE
Feature/Full File Uploads & Message Delete API

### PR DESCRIPTION
**Pull request by HenryHengZJ**
Ability for user to upload full file from the chat:

image

image

image

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
Pending changes from Embed & `api-documentation`  update

**Comment by boble23** [comment]
I am looking forward to this feature. It would be even more interesting if we could upload multiple documents. Perhaps we could limit the number of documents to avoid reaching the LLM threshold.

**Comment by vitusan** [comment]
@HenryHengZJ Hi! Been testing your branch because my use case benefits a lot from what you coded here. Although i was unable to activate this feature with agents. The chat inside flowise shows the attachment button when enabling full file uploads, but it won't receive the real file data, even using {{file_attachment}} as a promp value to be inserted in human prompt. After looking at it with langsmith, the {{file_attachment}} does show empty. Also, when using the ChatUI provided by flowise, the fileupload button won't show, after enabling the full file uploads. I'm attaching the chatflow JSON and some prints to help you identify the possible cause.
[devocional JB Agents (1).json](https://github.com/user-attachments/files/17438097/devocional.JB.Agents.1.json)
[flowise logs.txt](https://github.com/user-attachments/files/17438122/flowise.logs.txt)
image
image
image

**Comment by HenryHengZJ** [comment]
> Pending changes from Embed & `api-documentation` update

Embed PR: https://github.com/FlowiseAI/FlowiseChatEmbed/pull/268

**Pull request merged**
