### PR TITLE
fix: docker should install chromium and puppeteer should be no sandbox

### PR DESCRIPTION
**Pull request by AidanTilgner**
A couple of considerations here:

- 1) `--no-sandbox` means that puppeteer and chromium won't execute in a sandbox. This could theoretically have security implications, but since this is in a docker image I doubt it will matter. Maybe something to discuss further.
- 2) I'm not entirely sure the context around `ENV PUPPETEER_SKIP_DOWNLOAD=true` in the Dockerfile, although based on [this pr](https://github.com/FlowiseAI/Flowise/pull/350) it seems that the default install script was causing an error. I'm not seeing this error during build time here, and my thinking is through the Dockerfile there's more control anyway.

### CODE REVIEW

**Comment by AidanTilgner** [comment]
Also for consideration, the `headless: "new"` thing, I added to silence the current warning about the default headless mode switching in the future.

**Comment by chungyau97** [comment]
Results:
image
image
image

**Review by chungyau97 — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
@chungyau97 have you tried root Dockerfile, not the one inside `docker` folder

**Comment by chungyau97** [comment]
> @chungyau97 have you tried root Dockerfile, not the one inside `docker` folder

I copy the changes and use it in the root folder 
image

**Comment by chungyau97** [comment]
Results:
**Docker Folder**
Before
image
After

**Pull request merged**
