### PR TITLE
Marketplace: Revamped UI

### PR DESCRIPTION
**Pull request by vinodkiran**

### CODE REVIEW

**Review by KennyVaneetvelde — COMMENTED** [review]
👍 Excellent

**Comment by HenryHengZJ** [comment]
in list view, clicking template doesnt work: 
image

**Comment by HenryHengZJ** [comment]
should this be seperated out into another column?
image

**Comment by vinodkiran** [comment]
> in list view, clicking template doesnt work: image

Fixed.

**Comment by vinodkiran** [comment]
> should this be seperated out into another column? image

As it is part of the filter, I did not feel the need to have it as a separate column. Having it as a part of the nodes, is needed to make it searchable (search is on name, description and node)

**Comment by chungyau97** [comment]
Is it possible to add sorting in table header? 
image

For Example: 
  1. Clicking `Type` will sort with `Type asc, Name asc`
  2. Clicking `Type` 2nd time will sort with `Type desc, Name asc`

**Review by 0xi4o — APPROVED** [review]

**Comment by vinodkiran** [comment]
> Is it possible to add sorting in table header? 
> 
> image
> 
> 
> 
> For Example: 
> 
>   1. Clicking `Type` will sort with `Type asc, Name asc`
> 
>   2. Clicking `Type` 2nd time will sort with `Type desc, Name asc`
> 
> 

We will add sorting across all tables (flows, marketplace, variables, apikeys...etc) in a subsequent PR.

**Pull request merged**
