### PR TITLE
Use mysql2 to fix mysql connection issue for mysql 8

### PR DESCRIPTION
**Pull request by zhengcan**
Currently, the `server` component use `mysql` package.
It doesn't support MySQL 8 as server side.

Migrate to `mysql2` will fix related issues: #1782 .

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
@zhengcan thanks! some minor linting issue and lock file conflict

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
sorry @zhengcan there was a conflict with lock file, if you can resolve that'd be great, otherwise you can grant access for me to push to your branch i can resolve the conflict

**Comment by zhengcan** [comment]
> sorry @zhengcan there was a conflict with lock file, if you can resolve that'd be great, otherwise you can grant access for me to push to your branch i can resolve the conflict

I've merged source branch to the PR.
Please check it as your need.

**Comment by HenryHengZJ** [comment]
thank you @zhengcan !!

**Pull request merged**
