### PR TITLE
Added boolean flag which enables ssl connection for redis nodes.

### PR DESCRIPTION
**Pull request by tuxBurner**
This is needed for example connecting to the azure redis sever.

### CODE REVIEW

**Review by HenryHengZJ — APPROVED** [review]
thanks @tuxBurner !

**Comment by HenryHengZJ** [comment]
@tuxBurner some linting issue, would be great if you can run `yarn lint-fix`

**Comment by tuxBurner** [comment]
@HenryHengZJ sure thing.

Linting is done :)

Greetings

**Comment by tuxBurner** [comment]
:partying_face:

**Pull request merged**
