### PR TITLE
use URL constructor to handle all types of links

### PR DESCRIPTION
**Pull request by ape-nq**
This should enable to handle all types of relative URLs defined in RFC: https://www.rfc-editor.org/rfc/rfc3986#section-5.4

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
hmm can you give example where the particular link cant be scraped?

**Comment by ape-nq** [comment]
Example is in the issue.

I added screenshots for Release and patched version:
https://github.com/FlowiseAI/Flowise/issues/1741#issuecomment-1954120451

**Comment by ape-nq** [comment]
I also added a Chatflow to reproduce the example:
- https://github.com/FlowiseAI/Flowise/files/14310194/Relative.Link.Repro.Chatflow.json

**Comment by HenryHengZJ** [comment]
@chungyau97 can you take a look at this?

**Review by chungyau97 — APPROVED** [review]

**Comment by chungyau97** [comment]
Hi @ape-nq, thanks for the PR.

I wasn't aware that `URL()` will handle href and baseurl itself.
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#examples

**Comment by chungyau97** [comment]
Hi @ape-nq, you need to update your repo `main` branch and merge it into this branch to resolve run fail.

**Comment by ape-nq** [comment]
You're welcome!

Thank you and the other Flowise contributors! It really helped me to get started with RAG chatflows. Glad I could help by sending my fix upstream.

**Pull request merged**
