### PR TITLE
Maintenance/pnpm vite jsx (Enhancements to the Project Infrastructure)

### PR DESCRIPTION
**Pull request by use-the-fork**
I have made several significant updates to the project's foundation, aimed at improving efficiency and standardization. Here's a breakdown of the changes:

1. **Switch from Yarn to PNPM:** This change brings multiple advantages:
    - **Efficient Package Management:** With PNPM, `node_modules` are symlinked and shared, leading to the reuse of 2,860 packages.
    image
    - **Elimination of Turbo:** Turbo is removed as a dependency because PNPM inherently supports parallel execution.

2. **Committing a Lock File:** A lock file has been committed to ensure consistent package versions across different setups.

3. **Introduction of `kill-port` in Root `package.json`:** This utility ensures that ports are terminated before running the `dev` and `start` scripts, preventing port conflicts.

4. **Standardization of File Extensions in UI Folder:** Renamed `.js` files to `.jsx` to adhere to standard practices, enhancing code readability and maintainability.

5. **Replacement of Craco with Vite:** This upgrade introduces several improvements:
    - **Enhanced Hot Module Replacement (HMR):** Vite provides faster HMR, making development more efficient.
    - **Improved Packaging:** Vite offers better packaging strategies, enhancing overall performance.

6. **Adding `@/` Alias for UI Directory:** This alias simplifies referencing within the UI directory, improving code readability and organization.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
wow, these are all the stuff I wanted to upgrade but have not time yet, will definitely take a good look!

**Comment by HenryHengZJ** [comment]
sorry for the conflict, just merged in a PR, probably you have to update all the import path for the ui again

**Comment by use-the-fork** [comment]
@HenryHengZJ Take a look now. Both workflows should run now. Sorry lots of places needed updating to get this all to run.

**Comment by use-the-fork** [comment]
@HenryHengZJ I brought the branch up to date. Everything is looking good on my end only thing I changed was adding TSC-watch for server dev mode. It's much easier.

**Review by ocflowiseai — APPROVED** [review]
Looks good to me, thank you for the contribution!

**Pull request merged**
