### PR TITLE
Feature: Add configuration dialog for chatflow

### PR DESCRIPTION
**Pull request by 0xi4o**
- Adds a configuration dialog for chatflow with tabs for: rate limiting, speech to text, chat feedback, and allowed domains.

Flowise-Low-code-LLM-apps-builder (5)

Related: #1733 and #1765

### CODE REVIEW

**Comment by 0xi4o** [comment]
Sure. I can move them :+1:

**Comment by 0xi4o** [comment]
Moved Starter Prompts and Analyse Chatflow:

Flowise-Low-code-LLM-apps-builder (8)

**Comment by 0xi4o** [comment]
@HenryHengZJ I've pulled the latest changes and test this.

**Comment by HenryHengZJ** [comment]
pending task:
- Bring chat feedback, speech to text, allowed domains to table list view

**Comment by mokeyish** [comment]
It world be better to add a JSON configuration item, which can be accessed by `$config.xxx`(similar to `$vars.xxx`) and override by RESTful API calls.

**Comment by mokeyish** [comment]
> It world be better to add a JSON configuration item, which can be accessed by `$config.xxx`(similar to `$vars.xxx`) and override by RESTful API calls.

Currently, I do it by addding a FlowConfig node.

图片

But, this seems not a good idea.

**Review by HenryHengZJ — APPROVED** [review]

**Pull request merged**
