### PR TITLE
Support for ElasticSearch as a vector store

### PR DESCRIPTION
**Pull request by vinodkiran**

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
Were you able to get it working? @vinodkiran

**Comment by vinodkiran** [comment]
@HenryHengZJ 

There seems to be an issue with the underlying vector store implementation. I have raised a ticket with the langchain team.

https://github.com/langchain-ai/langchainjs/issues/2857

**Comment by vinodkiran** [comment]
@HenryHengZJ PR Is now complete...Kindly review and merge.

**Comment by vinodkiran** [comment]
The Underlying langchain vectorstore creates the following index. Kindly check your index in Elastic Cloud.

```javascript
{
  "mappings": {
    "dynamic_templates": [
      {
        "metadata.*": {
          "match_mapping_type": "*",
          "mapping": {
            "type": "keyword"
          }
        }
      }
    ],
    "properties": {
      "embedding": {
        "type": "dense_vector",
        "dims": 1536,
        "index": true,
        "similarity": "l2_norm",
        "index_options": {
          "type": "hnsw",
          "m": 16,
          "ef_construction": 100
        }
      },
      "metadata": {
        "properties": {
          "source": {
            "type": "keyword"
          }
        }
      },
      "text": {
        "type": "text"
      }
    }
  }
}
```

**Comment by HenryHengZJ** [comment]
ah it works now: 
image
image

Previously I created the index myself on ElasticSearch and that ran into error. So I specify a new index name that is not being created yet and have the underlying langchain implementation to create that index, that works.

**Review by HenryHengZJ — APPROVED** [review]
much appreciated for figuring out the issue and got it working!

**Comment by HenryHengZJ** [comment]
@vinodkiran the metadata filter is still not working right?

**Pull request merged**
