### PR TITLE
Feature/Add support for state-based metadata filter to Retriever Tool

### PR DESCRIPTION
**Pull request by serhiy-matoffo**
Extended Retriever Tool to support metadata filter based on the object stored in agent state.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
Interesting! do you have an example use case?

**Comment by serhiy-matoffo** [comment]
Sure. We've found that our RAG flow often returns irrelevant documents. To be a bit more precise, result documents contain some content related to some words used by the user but are found on documents on a completely different subject. So, we've tasked one of our LLM Nodes to figure out the subject of the conversation and save that to state (at this point we can form a metadata filter object). Later down the line, we would like to take that subject and use it to narrow down the query to the vector store.

Is there a way to implement this flow using existing functionality? I couldn't find one and had to add this property to a Retriever Tool.

**Comment by HenryHengZJ** [comment]
I was thinking of how to make it more generic..

How bout this? 
image

We can have an additional metadata filter, this adds to the existing filter from vector store if there is any. And users can filter using the existing flow variable such as `$flow.state`, `$flow.chatId` etc

**Comment by serhiy-matoffo** [comment]
This would not allow complex/nested filters, right?

**Comment by HenryHengZJ** [comment]
> This would not allow complex/nested filters, right?

Do you have an example of that? Under the hood it's just a simple JSON that adds on top of existing filter

**Comment by serhiy-matoffo** [comment]
>Do you have an example of that?

Here is an example from pinecone documentation: `{"$and": [{"genre": "comedy"}, {"genre":"documentary"}]}`

Would the functionality you suggested support this kind of syntax?

**Comment by HenryHengZJ** [comment]
yep definitely. If thats okay I can make the changes, you can then try it out

**Comment by serhiy-matoffo** [comment]
Sounds good!

**Comment by HenryHengZJ** [comment]
Updated, try and test see if it works @serhiy-matoffo

**Comment by serhiy-matoffo** [comment]
**I can confirm that it works great, thanks!** 

Also, this trick allows using any dynamic object from the flow state:

image

I just prefer to form that object using a script instead of typing in all the properties through those boxes 😄

**Review by HenryHengZJ — APPROVED** [review]
merging

**Comment by sirsimonson** [comment]
so excited to try this out

**Comment by sirsimonson** [comment]
@HenryHengZJ Also the above filter mechanism (which had worked through "Test Retrieval Query" doesnt work for this new feature. Somehow the filter is not passed down to the postgres query

**Comment by Sarahkunk** [comment]
Dynamic filtering is just what I was looking for. Has this been updated in cloud? Mine's showing older version still which doesn't have the filtering field: 

Screenshot 2024-11-26 at 11 59 38 AM


Screenshot 2024-11-26 at 12 00 59 PM

Trying it with pinecone but it doesn't pick up the dynamic values : 

Screenshot 2024-11-26 at 12 11 58 PM

Thankss

**Comment by Abdulwahab-17** [comment]
Can I get an example chatflow, Which i can modify to test this?

**Pull request merged**
