### PR TITLE
Fix JSON escaping (better)

### PR DESCRIPTION
**Pull request by mokeyish**
This PR fixes that #2461 cannot handle newline(`\r\n`) on windows.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
hmm by double stringify it? how does that work?

**Comment by mokeyish** [comment]
It will do the escaping thing.

**Comment by HenryHengZJ** [comment]
result: 
image

**Review by HenryHengZJ — APPROVED** [review]

**Comment by mokeyish** [comment]
> result: 结果： image

It seems that we should strip the `"` from the result.

**Comment by HenryHengZJ** [comment]
> @HenryHengZJ It seems that we should strip the `"` from the result.

yep, some users reported it doesnt work.

image
[Debug_Chatflow.json](https://github.com/user-attachments/files/15552309/Debug_Chatflow.json)

**Pull request merged**
