### PR TITLE
Fix for #911, CRLF line endings on Linux scripts.

### PR DESCRIPTION
**Pull request by automaton82**
As per https://github.com/FlowiseAI/Flowise/issues/911, the line endings on the Linux scripts are CRLF which do not work properly if a Docker build is created on Windows. To solve this, the line endings are converted to LF in source.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
awesome thanks @automaton82 for the fix!

**Comment by HenryHengZJ** [comment]
do you mind pulling latest changes from main branch to get the Node CI pass?

**Comment by automaton82** [comment]
Sure I did a sync just now. Hopefully that solves it.

**Comment by automaton82** [comment]
I think they passed now, so it seems to have worked.

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
Render deployment failed: 
image

Looks like we need to revert this

**Comment by automaton82** [comment]
Looks like a permissions issue on the file when in docker. But the permissions don't come from the host machine, so I'm not sure how it could be related. That's odd.

**Comment by HenryHengZJ** [comment]
Yeah, merged the revert PR and it fixed the issue. Not sure what was the cause of it

**Comment by automaton82** [comment]
Ok. I'll try to replicate. The way it is now won't docker run in Windows, so there must be a way to fix both.

**Comment by automaton82** [comment]
@HenryHengZJ I think I can fix this by following https://stackoverflow.com/questions/30195151/can-i-commit-specific-files-in-git-without-affecting-the-original-line-ending and adding a `.gitattributes` file into that folder targeting only `run` and `dev` files to have `LF` line endings. This would mean no changes to the actual files.

I have this working locally in Windows, but I'm now going to test it on Ubuntu WSL2 Linux. If it passes both of these, are you okay if I submit another PR with this file added to solve this instead of the failed way?

**Comment by automaton82** [comment]
Well I submitted a new PR #1077 which I tested to ensure it would run on Linux and Windows. It's a 1 file addition for git to deal with the line endings, and no changes to the actual files to avoid any permissions issues again.

Hopefully this is ok. It does fix it, as long as the file is touched by git (or re-cloned).

**Pull request merged**
