### PR TITLE
Feature/Add Print or Export Text Document Tool

### PR DESCRIPTION
**Pull request by yapwr**
This pull request adds a new tool named print_or_export_text_document to the marketplaces/tools directory. The tool utilizes the JotterPad public api to print or export text to document. Some of the supported input types include markdown, fountain and output types include pdf, docx, epub, zip.

For more details about how it works: [https://blog.jotterpad.app/flowise-jotterpads-print-engine/](https://blog.jotterpad.app/flowise-jotterpads-print-engine/)

For more details about the JotterPad API: [https://blog.jotterpad.app/introducing-jotterpad-cloud-printing-api/](https://blog.jotterpad.app/introducing-jotterpad-cloud-printing-api/)

### CODE REVIEW

**Comment by toi500** [comment]
Amazing!

**Comment by yapwr** [comment]
Apologies for the mistakes! Hopefully, the workflow will work this time.

**Comment by HenryHengZJ** [comment]
for linting issue, we can do `pnpm lint-fix`, lets see if it works this time

**Review by HenryHengZJ — APPROVED** [review]
thank you @yapwr !

**Pull request merged**
