### PR TITLE
feat(customtoolnode): add return direct to custom tool

### PR DESCRIPTION
**Pull request by patrickreinan**
Added return direct option to CustomTool node.

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
1 bug we have by returning direct is that, it still streams the output from LLM:
image

But if you close the chat window and open again, it will shows the output returned directly from custom tool:
image

**Comment by patrickreinan** [comment]
@HenryHengZJ this image is different from version that I have pushed. I added a checkbox to turn return direct on. 

I am using this version and I am not facing this issue. I will check with latest branch main version.

**Comment by patrickreinan** [comment]
@HenryHengZJ I could reproduce the issue here. I will check what is happening and fix the issue.

**Comment by HenryHengZJ** [comment]
> @HenryHengZJ this image is different from version that I have pushed. I added a checkbox to turn return direct on.
> 
> I am using this version and I am not facing this issue. I will check with latest branch main version.

oh yeah I was harcoding returnDirect to true in the code so

**Comment by patrickreinan** [comment]
I got it. 😉

**Comment by patrickreinan** [comment]
@HenryHengZJ I did some changes in my code. I figured out that when agent try to call a custom tool with return direct with invalid parameters, automatically a empty text was being returned in a JSON format. I think this was the cause the bug that you have mentioned.

**Comment by HenryHengZJ** [comment]
hey @patrickreinan sorry for late response. I've added this PR that solve the issue: https://github.com/FlowiseAI/Flowise/pull/3003, feel free to try it out and see if that works correctly. Closing this for now

**Comment by patrickreinan** [comment]
😉

**Pull request closed without merging**
