### PR TITLE
Fix llm instanceof wrong ChatOpenAI type

### PR DESCRIPTION
**Pull request by mokeyish**
update 
```ts
import { ChatOpenAI } from '../../chatmodels/ChatOpenAI/FlowiseChatOpenAI'
```
to 
```ts
import { ChatOpenAI } from '@langchain/openai'
```

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
it is the correct import, `FlowiseChatOpenAI` is needed for `multiModalOption`

**Comment by mokeyish** [comment]
> it is the correct import, `FlowiseChatOpenAI` is needed for `multiModalOption`

I see that the actual instance of llm is LanhchainChatOpenAI. Should logical OR be used here?

**Comment by HenryHengZJ** [comment]
> > it is the correct import, `FlowiseChatOpenAI` is needed for `multiModalOption`
> 
> I see that the actual instance of llm is LanhchainChatOpenAI. Should logical OR be used here?

which line?

**Comment by mokeyish** [comment]
> > > it is the correct import, `FlowiseChatOpenAI` is needed for `multiModalOption`
> > 
> > 
> > I see that the actual instance of llm is LanhchainChatOpenAI. Should logical OR be used here?
> 
> which line?

https://github.com/FlowiseAI/Flowise/blob/15a416a58f4865a07b35443a563d546e31e92d47/packages/components/nodes/multiagents/Supervisor/Supervisor.ts#L225

**Comment by mokeyish** [comment]
@HenryHengZJ Is there any problem with this?

**Comment by HenryHengZJ** [comment]
if you look at this [line](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/multiagents/Supervisor/Supervisor.ts#L419), `llm.multiModalOption` is only a method from the custom `FlowiseChatOpenAI` [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chatmodels/ChatOpenAI/FlowiseChatOpenAI.ts#L32)

so for any LLMs that is able to process images, we need the custom override class, cant use the direct import

**Pull request closed without merging**
