### PR TITLE
feat (server)： add support for setting listening host

### PR DESCRIPTION
**Pull request by mokeyish**

### CODE REVIEW

**Comment by HenryHengZJ** [comment]
why the need to listen for host?

**Comment by mokeyish** [comment]
> why the need to listen for host?

Because in development mode, the UI will proxy this address. I hope to configure it to listen to 127.0.0.1

**Comment by mokeyish** [comment]
Could you merge this PR？ do you have any other concerns? 

If `HOST` not defined, its behavior is the same as before the change.

My local code has these changes, and it is troublesome to synchronize the code every time.

**Review by HenryHengZJ — APPROVED** [review]

**Comment by HenryHengZJ** [comment]
@mokeyish sorry was held up by other things, just approved!

**Pull request merged**
